<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.6</version>
        <relativePath/>
    </parent>
    <groupId>com.ohmygod</groupId>
    <artifactId>shop-agent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>shop-agent</name>
    <description>Shop Agent aggregated project</description>
    <modules>
        <module>shop-agent-common</module>
        <module>shop-agent-id-generator-framework</module>
        <module>shop-agent-redis-tool-framework</module>
        <module>shop-agent-redisson-framework</module>
        <module>shop-agent-business</module>
    </modules>
    <properties>
        <java.version>17</java.version>
        <redisson.version>3.32.0</redisson.version>
        <hutool.version>5.8.25</hutool.version>
        <fastjson.version>1.2.83</fastjson.version>
        <commons-lang.version>2.6</commons-lang.version>
        <openapi.swagger.version>2.2.0</openapi.swagger.version>
        <minio.version>8.5.17</minio.version>
        <mybatis-plus.version>3.5.17</mybatis-plus.version>
    </properties>
</project>
