<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ohmygod</groupId>
        <artifactId>shop-agent-redisson-service-framework</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>shop-agent-repeat-execute-limit-framework</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.ohmygod</groupId>
            <artifactId>shop-agent-redisson-common-framework</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ohmygod</groupId>
            <artifactId>shop-agent-service-lock-framework</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
